---
- name: Installs ansible jenkins plugin 
  hosts: all 
  gather_facts: no
  become: true
  tasks:

  - name: Install Ansible plugins
    jenkins_plugin:
      name: "{{ item }}"
      url_username: "{{ jenkins_username }}"
      url_password: "{{ jenkins_password }}"
      url: "{{ jenkins_url }}" 
    with_items:
      - AnsiColor
      - ansible
      - ansible-tower
    register: plugin_install

  - name: Install Ansible Tower plugin
    jenkins_plugin:
      name: "Ansible Tower"
      url_username: "{{ jenkins_username }}"
      url_password: "{{ jenkins_password }}"
      url: "{{ jenkins_url }}"
    register: plugin_install
    
  - name: Restart Jenkins
    service:
      name: jenkins
      state: restarted
    when: plugin_install.changed
