---

- name: Grab the GPG Key
  shell: sudo rpm --import "https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e"

- name: Enable Repository for Docker Install
  shell: sudo yum-config-manager --add-repo https://packages.docker.com/1.12/yum/repo/main/centos/7 

- name: Install Docker Engine
  yum:
    name: "docker-engine"
    state: installed
  notify: restart docker

- name: Make sure /etc/docker exists
  file:
    path: /etc/docker
    state: directory

- name: Push out our daemon.json file
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker
